version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"

  flask:
    build: .
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    command: python main.py